apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: todo-app
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: backend
          image: kajal4321/todo-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "database-service"
