apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    namespace: todo-app
    labels:
      app: todoapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: frontend
          image: kajal4321/todo-frontend:clean
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service:3000"

