apiVersion: v1
kind: Service
metadata:
    name: backend
    labels:
      app: todoapp
spec:
  selector:
    app: todoapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000    
  type: ClusterIP
